# 
# Copyright (C) 2021  CismonX <admin@cismon.net>
# 
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
# 

kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: pureos/amber-slim
    commands:
      - apt -y install build-essential autoconf automake dejagnu 
      - autoreconf --install
      - ./configure CFLAGS='-O0 -g -std=c99 -Wall -Wextra -Wpedantic --coverage'
      - make
      - make check
      - gcov src/*.c
