language: c

os:
  - linux
  - osx

dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - dejagnu
  homebrew:
    update: true
    packages:
      - dejagnu

branches:
  only:
    - master

script:
  - autoreconf --install
  - ./configure
  - make
  - make check
  - sudo make install
  - command -v u6a u6ac
# - whatis u6a u6ac      # broken on macOS...
