# 
# Copyright (C) 2020  CismonX <admin@cismon.net>
# 
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
# 

language: c

os:
  - linux
  - osx

dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
      - dejagnu
  homebrew:
    update: true
    packages:
      - dejagnu

branches:
  only:
    - master

before_script:
  - export GCOV_BIN=`test $TRAVIS_COMPILER = clang && echo 'llvm-cov gcov' || echo gcov`
  - test $TRAVIS_OS_NAME = osx && export PATH=$PATH:/Library/Developer/CommandLineTools/usr/bin || true

script:
  - autoreconf --install
  - ./configure CFLAGS='-O0 -g -Wall -Wextra -Wpedantic -coverage'
  - make
  - make check
  - $GCOV_BIN src/*.c
  - sudo make install
  - command -v u6a u6ac
# - whatis u6a u6ac      # broken on macOS...

after_success:
  - test $TRAVIS_OS_NAME = osx && true || bash <(curl -s https://codecov.io/bash)
