language: c

os:
  - linux
  - osx

dist: bionic

sudo: required

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - autoreconf --install
  - ./configure
  - make
  - make check
  - sudo make install
  - command -v u6a u6ac
# - whatis u6a u6ac      # broken on macOS...
